CREATE OR REPLACE FUNCTION public.processar_analise_diagnostico_estoque_grupo_diario()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    rec_produto record;
    guardar_log_historico_diagnostico_data_atual bool;
BEGIN
    
    IF (SELECT min(aplicado) AS REF FROM tempo_cobertura_compras_geral WHERE tempo_cobertura > 0 AND deleted_at IS NULL) IS NULL THEN
        RETURN;
    END IF;
    
    -- verifica se é pra guardar historico do dia atual
    SELECT MOD(current_date - COALESCE(max(v.DATA), current_date), (SELECT qtde_dias_log_historico_diagnostico FROM cfgsystem)) = 0 INTO guardar_log_historico_diagnostico_data_atual 
    FROM analise_diagnostico_estoque_grupo_diario v;

    -- cancela o log do dia atual
    IF NOT guardar_log_historico_diagnostico_data_atual THEN
        RETURN;
    END IF;
    
    FOR rec_produto IN (SELECT * FROM analise_diagnostico_estoque_grupo)
    LOOP
        UPDATE public.analise_diagnostico_estoque_grupo_diario
        SET
            descricao_grupo = rec_produto.descricao_grupo,
            idsegmento = rec_produto.idsegmento,
            descricao_segmento = rec_produto.descricao_segmento,
            idsecao = rec_produto.idsecao,
            descricao_secao = rec_produto.descricao_secao,
            idcomprador = rec_produto.idcomprador,
            descricao_comprador = rec_produto.descricao_comprador,
            idfornecedor = rec_produto.idfornecedor,
            descricao_fornecedor = rec_produto.descricao_fornecedor,
            descricao_produto = rec_produto.descricao_produto,
            data_cadastro = rec_produto.data_cadastro,
            preco_custo = rec_produto.preco_custo,
            preco_venda = rec_produto.preco_venda,
            data_ult_saida = rec_produto.data_ult_saida,
            qtde_dias_sem_vender = rec_produto.qtde_dias_sem_vender,
            estoque = rec_produto.estoque,
            esseg = rec_produto.esseg,
            pp = rec_produto.pp,
            emax = rec_produto.emax,
            consumo_medio_mensal = rec_produto.consumo_medio_mensal,
            consumo_medio_diario = rec_produto.consumo_medio_diario,
            classificacao_financeira = rec_produto.classificacao_financeira,
            classificacao_popularidade = rec_produto.classificacao_popularidade,
            classificacao_criticidade = rec_produto.classificacao_criticidade,
            classificacao_comprabilidade = rec_produto.classificacao_comprabilidade,
            nivel_servico = rec_produto.nivel_servico,
            tempo_medio_apanhe = rec_produto.tempo_medio_apanhe,
            estoque_transito = rec_produto.estoque_transito,
            id_solicitacao = rec_produto.id_solicitacao,
            data_solicitacao = rec_produto.data_solicitacao,
            data_previsao = rec_produto.data_previsao,
            ativo_para_venda = rec_produto.ativo_para_venda,
            fora_de_linha = rec_produto.fora_de_linha,
            tempo_ressuprimento_meses = rec_produto.tempo_ressuprimento_meses,
            tempo_ressuprimento_dias = rec_produto.tempo_ressuprimento_dias,
            cobertura_emax = rec_produto.cobertura_emax,
            emax_em_preco_custo = rec_produto.emax_em_preco_custo,
            cobertura_estoque = rec_produto.cobertura_estoque,
            estoque_em_preco_custo = rec_produto.estoque_em_preco_custo,
            estoque_em_preco_venda = rec_produto.estoque_em_preco_venda,
            cmm_em_preco_venda = rec_produto.cmm_em_preco_venda,
            cmm_em_preco_custo = rec_produto.cmm_em_preco_custo,
            estoque_em_excesso = rec_produto.estoque_em_excesso,
            estoque_em_excesso_em_preco_custo = rec_produto.estoque_em_excesso_em_preco_custo,
            data_analise_demanda_real = rec_produto.data_analise_demanda_real,
            sugestao_compra = rec_produto.sugestao_compra,
            sugestao_compra_preco_custo = rec_produto.sugestao_compra_preco_custo,
            qtde_dias_cobertura_parametrizada = rec_produto.qtde_dias_cobertura_parametrizada,
            markup = rec_produto.markup,
            frequencia_saida = rec_produto.frequencia_saida,
            faturamento = rec_produto.faturamento,
            status_produto = rec_produto.status_produto,
            grupo_intervalo_cobertura = rec_produto.grupo_intervalo_cobertura,
            histograma = rec_produto.histograma,
            idade = rec_produto.idade,
            data_cobertura_instatanea = rec_produto.data_cobertura_instatanea,
            status_demanda = rec_produto.status_demanda,
            demanda_real = rec_produto.demanda_real,
            dif_data = rec_produto.dif_data,
            faturamento_real = rec_produto.faturamento_real,
            diferenca = rec_produto.diferenca,
            cobertura_parametrizavel = rec_produto.cobertura_parametrizavel,
            estoque_parametrizavel = rec_produto.estoque_parametrizavel,
            estoque_parametrizavel_preco_custo = rec_produto.estoque_parametrizavel_preco_custo,
            total_estoque_para_aumentar = rec_produto.total_estoque_para_aumentar,
            total_estoque_para_reduzir = rec_produto.total_estoque_para_reduzir,
            total_estoque_para_aumentar_preco_custo = rec_produto.total_estoque_para_aumentar_preco_custo,
            total_estoque_para_reduzir_preco_custo = rec_produto.total_estoque_para_reduzir_preco_custo,
            emax_parametrizavel = rec_produto.emax_parametrizavel,
            estoque_em_excesso_parametrizavel = rec_produto.estoque_em_excesso_parametrizavel,
            estoque_em_excesso_parametrizavel_em_preco_custo = rec_produto.estoque_em_excesso_parametrizavel_em_preco_custo,
            consumo_transito = rec_produto.consumo_transito,
            consumo_transito_preco_custo = rec_produto.consumo_transito_preco_custo,
            estoque_residual = rec_produto.estoque_residual,
            estoque_futuro_preco_custo = rec_produto.estoque_futuro_preco_custo,
            estoque_minimo = rec_produto.estoque_minimo,
            data_primeira_entrada = rec_produto.data_primeira_entrada,
            data_ultima_entrada = rec_produto.data_ultima_entrada,
            classificacao_rentabilidade = rec_produto.classificacao_rentabilidade,
            produto_combinado = rec_produto.produto_combinado,
            cod_produto = rec_produto.cod_produto
        WHERE
            idgrupo = rec_produto.idgrupo
            AND idproduto = rec_produto.idproduto
            AND data = CURRENT_DATE;

        IF NOT FOUND THEN
            INSERT INTO public.analise_diagnostico_estoque_grupo_diario (
                idgrupo,
                descricao_grupo,
                idsegmento,
                descricao_segmento,
                idsecao,
                descricao_secao,
                idcomprador,
                descricao_comprador,
                idfornecedor,
                descricao_fornecedor,
                idproduto,
                descricao_produto,
                data_cadastro,
                preco_custo,
                preco_venda,
                data_ult_saida,
                qtde_dias_sem_vender,
                estoque,
                esseg,
                pp,
                emax,
                consumo_medio_mensal,
                consumo_medio_diario,
                classificacao_financeira,
                classificacao_popularidade,
                classificacao_criticidade,
                classificacao_comprabilidade,
                nivel_servico,
                tempo_medio_apanhe,
                estoque_transito,
                id_solicitacao,
                data_solicitacao,
                data_previsao,
                ativo_para_venda,
                fora_de_linha,
                tempo_ressuprimento_meses,
                tempo_ressuprimento_dias,
                cobertura_emax,
                emax_em_preco_custo,
                cobertura_estoque,
                estoque_em_preco_custo,
                estoque_em_preco_venda,
                cmm_em_preco_venda,
                cmm_em_preco_custo,
                estoque_em_excesso,
                estoque_em_excesso_em_preco_custo,
                data_analise_demanda_real,
                sugestao_compra,
                sugestao_compra_preco_custo,
                qtde_dias_cobertura_parametrizada,
                markup,
                frequencia_saida,
                faturamento,
                status_produto,
                grupo_intervalo_cobertura,
                histograma,
                idade,
                data_cobertura_instatanea,
                status_demanda,
                demanda_real,
                dif_data,
                faturamento_real,
                diferenca,
                cobertura_parametrizavel,
                estoque_parametrizavel,
                estoque_parametrizavel_preco_custo,
                total_estoque_para_aumentar,
                total_estoque_para_reduzir,
                total_estoque_para_aumentar_preco_custo,
                total_estoque_para_reduzir_preco_custo,
                emax_parametrizavel,
                estoque_em_excesso_parametrizavel,
                estoque_em_excesso_parametrizavel_em_preco_custo,
                consumo_transito,
                consumo_transito_preco_custo,
                estoque_residual,
                estoque_futuro_preco_custo,
                DATA,
                estoque_minimo,
                data_primeira_entrada,
                data_ultima_entrada,
                classificacao_rentabilidade,
                produto_combinado,
                cod_produto
             )
            VALUES(
                rec_produto.idgrupo,
                rec_produto.descricao_grupo,
                rec_produto.idsegmento,
                rec_produto.descricao_segmento,
                rec_produto.idsecao,
                rec_produto.descricao_secao,
                rec_produto.idcomprador,
                rec_produto.descricao_comprador,
                rec_produto.idfornecedor,
                rec_produto.descricao_fornecedor,
                rec_produto.idproduto,
                rec_produto.descricao_produto,
                rec_produto.data_cadastro,
                rec_produto.preco_custo,
                rec_produto.preco_venda,
                rec_produto.data_ult_saida,
                rec_produto.qtde_dias_sem_vender,
                rec_produto.estoque,
                rec_produto.esseg,
                rec_produto.pp,
                rec_produto.emax,
                rec_produto.consumo_medio_mensal,
                rec_produto.consumo_medio_diario,
                rec_produto.classificacao_financeira,
                rec_produto.classificacao_popularidade,
                rec_produto.classificacao_criticidade,
                rec_produto.classificacao_comprabilidade,
                rec_produto.nivel_servico,
                rec_produto.tempo_medio_apanhe,
                rec_produto.estoque_transito,
                rec_produto.id_solicitacao,
                rec_produto.data_solicitacao,
                rec_produto.data_previsao,
                rec_produto.ativo_para_venda,
                rec_produto.fora_de_linha,
                rec_produto.tempo_ressuprimento_meses,
                rec_produto.tempo_ressuprimento_dias,
                rec_produto.cobertura_emax,
                rec_produto.emax_em_preco_custo,
                rec_produto.cobertura_estoque,
                rec_produto.estoque_em_preco_custo,
                rec_produto.estoque_em_preco_venda,
                rec_produto.cmm_em_preco_venda,
                rec_produto.cmm_em_preco_custo,
                rec_produto.estoque_em_excesso,
                rec_produto.estoque_em_excesso_em_preco_custo,
                rec_produto.data_analise_demanda_real,
                rec_produto.sugestao_compra,
                rec_produto.sugestao_compra_preco_custo,
                rec_produto.qtde_dias_cobertura_parametrizada,
                rec_produto.markup,
                rec_produto.frequencia_saida,
                rec_produto.faturamento,
                rec_produto.status_produto,
                rec_produto.grupo_intervalo_cobertura,
                rec_produto.histograma,
                rec_produto.idade,
                rec_produto.data_cobertura_instatanea,
                rec_produto.status_demanda,
                rec_produto.demanda_real,
                rec_produto.dif_data,
                rec_produto.faturamento_real,
                rec_produto.diferenca,
                rec_produto.cobertura_parametrizavel,
                rec_produto.estoque_parametrizavel,
                rec_produto.estoque_parametrizavel_preco_custo,
                rec_produto.total_estoque_para_aumentar,
                rec_produto.total_estoque_para_reduzir,
                rec_produto.total_estoque_para_aumentar_preco_custo,
                rec_produto.total_estoque_para_reduzir_preco_custo,
                rec_produto.emax_parametrizavel,
                rec_produto.estoque_em_excesso_parametrizavel,
                rec_produto.estoque_em_excesso_parametrizavel_em_preco_custo,
                rec_produto.consumo_transito,
                rec_produto.consumo_transito_preco_custo,
                rec_produto.estoque_residual,
                rec_produto.estoque_futuro_preco_custo,
                CURRENT_DATE,
                rec_produto.estoque_minimo,
                rec_produto.data_primeira_entrada,
                rec_produto.data_ultima_entrada,
                rec_produto.classificacao_rentabilidade,
                rec_produto.produto_combinado,
                rec_produto.cod_produto
            );
        END IF;
    END LOOP;
END;
$function$

